create table if not exists public.portfolio_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254),
  message text not null check (char_length(message) between 1 and 5000),
  status text not null default 'new' check (status in ('new', 'read', 'replied', 'archived')),
  source text not null default 'portfolio',
  created_at timestamptz not null default now()
);

alter table public.portfolio_messages enable row level security;
grant insert on table public.portfolio_messages to anon;
grant usage, select on sequence public.portfolio_messages_id_seq to anon;

create policy "Public can submit portfolio messages"
on public.portfolio_messages for insert to anon
with check (source = 'portfolio');
